var fromValue;
var toValue;
    $("#select-choice-from").on('change',function(){
        fromValue = $(this).val();
        console.log("from value "+  fromValue);
    });
    $("#select-choice-to").on('change',function(){
        toValue = $(this).val();
    });                 
    $("#loadBTN").click(function(){

//page 16
 if(fromValue =="16" && toValue == "17"){
    $.mobile.changePage("#gg01" , {transition: "slideup"});
}
else if(fromValue =="16" && toValue == "18"){
    $.mobile.changePage("#gg02" , {transition: "slideup"});
}
else if(fromValue =="16" && toValue == "19"){
    $.mobile.changePage("#gg03" , {transition: "slideup"});
}
else if(fromValue =="16" && toValue == "20"){
    $.mobile.changePage("#gg04" , {transition: "slideup"});
}
else if(fromValue =="16" && toValue == "21"){
    $.mobile.changePage("#gg05" , {transition: "slideup"});
}
else if(fromValue =="16" && toValue == "22"){
    $.mobile.changePage("#gg06" , {transition: "slideup"});
}
else if(fromValue =="16" && toValue == "23"){
    $.mobile.changePage("#gg07" , {transition: "slideup"});
}
else if(fromValue =="16" && toValue == "24"){
    $.mobile.changePage("#gg08" , {transition: "slideup"});
}
else if(fromValue =="16" && toValue == "25"){
    $.mobile.changePage("#gg09" , {transition: "slideup"});
}
else if(fromValue =="16" && toValue == "26"){
    $.mobile.changePage("#gg10" , {transition: "slideup"});
}
else if(fromValue =="16" && toValue == "27"){
    $.mobile.changePage("#gg11" , {transition: "slideup"});
}
else if(fromValue =="16" && toValue == "28"){
    $.mobile.changePage("#gg12" , {transition: "slideup"});
}
else if(fromValue =="16" && toValue == "29"){
    $.mobile.changePage("#gg13" , {transition: "slideup"});
}
else if(fromValue =="16" && toValue == "30"){
    $.mobile.changePage("#gg14" , {transition: "slideup"});
}
else if(fromValue =="16" && toValue == "31"){
    $.mobile.changePage("#gg15" , {transition: "slideup"});
}
else if(fromValue =="16" && toValue == "32"){
    $.mobile.changePage("#gg16" , {transition: "slideup"});
}
else if(fromValue =="16" && toValue == "33"){
    $.mobile.changePage("#gg17" , {transition: "slideup"});
}
else if(fromValue =="16" && toValue == "34"){
    $.mobile.changePage("#gg18" , {transition: "slideup"});
}
else if(fromValue =="16" && toValue == "35"){
    $.mobile.changePage("#gg19" , {transition: "slideup"});
}
else if(fromValue =="16" && toValue == "1"){
    $.mobile.changePage("#gg20" , {transition: "slideup"});
}
else if(fromValue =="16" && toValue == "2"){
    $.mobile.changePage("#gg21" , {transition: "slideup"});
}
else if(fromValue =="16" && toValue == "3"){
    $.mobile.changePage("#gg22" , {transition: "slideup"});
}
else if(fromValue =="16" && toValue == "4"){
    $.mobile.changePage("#gg23" , {transition: "slideup"});
}
else if(fromValue =="16" && toValue == "5"){
    $.mobile.changePage("#gg24" , {transition: "slideup"});
}
else if(fromValue =="16" && toValue == "6"){
    $.mobile.changePage("#gg25" , {transition: "slideup"});
}
else if(fromValue =="16" && toValue == "7"){
    $.mobile.changePage("#gg26" , {transition: "slideup"});
}
else if(fromValue =="16" && toValue == "8"){
    $.mobile.changePage("#gg27" , {transition: "slideup"});
}
else if(fromValue =="16" && toValue == "9"){
    $.mobile.changePage("#gg28" , {transition: "slideup"});
}
else if(fromValue =="16" && toValue == "10"){
    $.mobile.changePage("#gg29" , {transition: "slideup"});
} 
else if(fromValue =="16" && toValue == "11"){
    $.mobile.changePage("#gg30" , {transition: "slideup"});
} 
else if(fromValue =="16" && toValue == "12"){
    $.mobile.changePage("#gg31" , {transition: "slideup"});
}
else if(fromValue =="16" && toValue == "13"){
    $.mobile.changePage("#gg32" , {transition: "slideup"});
}
else if(fromValue =="16" && toValue == "14"){
    $.mobile.changePage("#gg33" , {transition: "slideup"});
}
else if(fromValue =="16" && toValue == "15"){
    $.mobile.changePage("#gg34" , {transition: "slideup"});
}
    });